name: 'Add Stonk'
on:
  issues:
    types: [opened]

defaults:
  run:
    working-directory: ./data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run addticker -- "${{ toJSON(github.event.issue) }}"
    - name: Committing changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Github Actions
        author_email: actions@github.com